### ISSUE TITLE
Provide feedback on setup process $@100000

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-stack#24]
Submit notes on any points in the stack setup process that are confusing or broken.

**Comment by Lombitron** [comment]
So I've got two bits so far, first my thoughts about what I would have found helpful to fill in gaps in my knowledge and get up-2- speed, and second my notes I've made as I've been setting up a new dev environment and attempting my 1st changes to the code:

**Comment by Lombitron** [comment]
=What I would have found handy=
 - list of the projects 
   - their function
   - tech stack of project
   - who to talk to about this project, i.e. contacts
   - what other project do they depend on / interface with
   - what functionality has been developed so far for this project
   - what functionality is the current target development for this project
   - what are the features working towards for this project

 - where to get help - general
   - https://tribes.sphinx.chat/t/developingonsphinx

**Comment by Lombitron** [comment]
=dev env setup=
==Sphinx-Stack==
`git clone https://github.com/stakwork/sphinx-stack.git`
'docker-compose up -d'

if all is ok - need the client 
`docker-compose ps`

open `relay/NODES.json` (if it's not got exported key values - something is wrong)

if something isnt right:
'docker-compose down'
'./clearAll.sh' 
'docker-compose up -d'

==sphinx-win-linux-desktop==

`git clone https://github.com/stakwork/sphinx-win-linux-desktop`
`npn install`

I got this error:
```
steve@hulk:~/repos/sphinx2/sphinx-win-linux-desktop$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sphinx@0.1.0
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@"^15.0.0 || ^16.0.0" from @cleandersonlobo/react-mic@1.2.0
npm ERR!   node_modules/@cleandersonlobo/react-mic
npm ERR!     @cleandersonlobo/react-mic@"^1.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.14.0" from react-dom@16.14.0
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^16.9.0" from the root project
npm ERR!   peer react-dom@"^15.0.0 || ^16.0.0" from @cleandersonlobo/react-mic@1.2.0
npm ERR!   node_modules/@cleandersonlobo/react-mic
npm ERR!     @cleandersonlobo/react-mic@"^1.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/steve/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steve/.npm/_logs/2022-03-16T21_59_21_699Z-debug-0.log
```

resolve it with `npm install --legacy-peer-deps`

rest is in `README.md` for `Desktop dev:`

connect to `sphinx-stack`
 - `cat sphinx-stack/relay/NODES.json`
 - copy a `"exported_key"` into client and connect ( PIN is in NODES.json as well)
 - add contacts woth other `pubkey` from `NODES.json`

 - how to craete a tribe ? / join tribe?


 ==sphinx-tribes==

  - `git clone https://github.com/stakwork/sphinx-tribes.git`

2 options 
 - kevkevin:
   1.) make changes in tribes 
   2.) make new docker build ie run `go build` run `docker build -t sphinxlightning/sphinx-tribes .` 
   then go to ‘sphinx-stack’ repo and run docker-compose up -d (should update with new image) 
   3.) check to see if the changes are reflected

 - what ive been doing:
  sphinx-tribes: create a .env file from docker-compose & add to dockerfile
  sphinx-stack: `docker-compose -f ./alts/no-tribes.yml --project-directory . up -d`

  then you can either `go build ...` or `docker build ....`
  `go build ...` means you can use a debugger in your IDE


 running tribes web front end

 something to do with the “getHostIncludingDockerHosts” function
It looks like he set PORT=5002 in the “tribes” image instead of 13000

kevkevin: ok, so I was able to get tribes frontend running locally by switching PORT to 5002 in the stack and then I run `ngrok http 5002` then use the output of that in the host.ts file and just return that instead of the localhost:5002
You can make a github Personal Access Token to test (donest need any special scopes)and just put it in env as GITHUB_TOKEN

=making changes=
- fork stakwork repo
- add new origin to my fork, 
- make changes
- push to my fork
- create PR to merge to master of stakwork repo
